services:
  bahnhof-watchdog:
    container_name: bahnhof-watchdog
    image: musenkishi/bahnhof-watchdog:latest
    ports:
      - 3000:3000
    volumes:
      - data:/data
    env_file:
      - .env

volumes:
  data:
